### ISSUE TITLE
您好楼主，请教一个问题

### ISSUE THREAD

**Issue by xhochipe** [liu-cn/json-filter#10]
如题。其实很多时候为了方便，都把比如什么场景，返回什么字段，为灵活都配置到数据库，其实比如根据数据库配置到字段，动态映射到select 或者omit里面，这样更方便

**Comment by liu-cn** [comment]
你提的问题很好，不过我希望你能再详细描述一番，如果每次返回数据都从数据库再获取一遍场景的配置信息就很麻烦了，不过我倒是希望你能说一下你构思的大概用法是什么样的，我目前没有遇到类似需求所以理解所以可能我很难一时半会想出一个好的解决方案。

**Comment by xhochipe** [comment]
@liu-cn 其实每次可以load到内存里面或者redis里面，这样更方便，方便加个微信好友吗，其实我之前看到过一些这样的思路，但是都是在结构体之外配置字段，然后一个个字段遍历校验的

**Comment by liu-cn** [comment]
微信号：lbl3317

**Comment by liu-cn** [comment]
closed

**Comment by liu-cn** [comment]
closed
