### ISSUE TITLE
Ptr Nil panic

### ISSUE THREAD

**Issue by iTryIt** [liu-cn/json-filter#15]
Nil Ptr cause panic
指针未做nil判断会导致panic

file: filter/parser.go
line: 19 to 22

Test：
```golang
type T struct {
    A string `json:"a,select(test)"`
}

func TestNil(t *testing.T) {
    var a *T
    var el = map[string]any{
        "a": a, // a: nil ptr
    }

    fmt.Println(filter.Select("test", el))
}
```

**Comment by liu-cn** [comment]
感谢反馈，2小时内会发布新版本修复该问题












刘北洛
***@***.***

go开发

---Original---
From: ***@***.***&gt;
Date: Fri, Dec 15, 2023 21:01 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [liu-cn/json-filter] Ptr  (Issue #15)




 
Nil Ptr cause panic
 指针未做nil判断会导致panic
 
file: filter/parser.go
 line: 19 to 22
 
Test：
 type T struct {     A string `json:"a,select(test)"` } func TestNil(t *testing.T) {     var a *T     var el = map[string]any{         "a": a, // a: nil ptr     }     fmt.Println(filter.Select("test", el)) }

**Comment by iTryIt** [comment]
我提交了一个pull request，你检查一下我的写法是否OK

**Comment by liu-cn** [comment]
好的，感谢，刚到家，正在看












刘北洛
***@***.***

go开发

---Original---
From: ***@***.***&gt;
Date: Fri, Dec 15, 2023 21:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [liu-cn/json-filter] Ptr Nil panic (Issue #15)




 
我提交了一个pull request，你检查一下我的写法是否OK

**Comment by liu-cn** [comment]
发布新版本v1.17 已修复该问题，感谢反馈
https://github.com/liu-cn/json-filter/releases/tag/v1.17
https://github.com/liu-cn/json-filter/pull/16
