### ISSUE TITLE
你好，作者，我对序列化这里有一个问题请教

### ISSUE THREAD

**Issue by xxzhwl** [liu-cn/json-filter#2]
我们知道GoLang中的Json库做序列化和反序列化之后，如果结构体字段为零值，使用‘omitempty’可以让该字段结果被忽视。“json-filter"提供的方法中，我尝试了一下，是不能做到的，想问一下，这个问题后续可以解决吗？

**Comment by liu-cn** [comment]
你好，目前是支持为nil类型直接忽略的，这个：Nickname *string `json:"nickname,omitempty,select(article|profile)"`
Nickname是个string类型的指针，如果携带omitempty是可以直接忽略的，如果是string类型Nickname string `json:"nickname,omitempty,select(article|profile)"`，目前是没法直接忽略的，为初始值忽略这个功能也是能够实现的，只是我没有这么做，因为空字符串“”和nil本身是两种含义，所以只做了为nil忽略，为初始值是没做忽略操作的，比如int类型为0时不会忽略，string为0是也不会被忽略，如果想要这个功能的话后面也可以考虑加入，但是不确定这样真的好不好。

**Comment by liu-cn** [comment]
你好这个功能已经添加了，这时候你再重新下载一下包试一下呗，这时是可以忽略零值字段的。

**Comment by xxzhwl** [comment]
了解。因为我是最近刚入门golang的，对这个问题还有点奇怪。如果我们数据库有那些不设置”not null“的字段，是要在Struct定义时用指针类型吗？否则取出来的数据我该怎么知道它是null 还是 0呢？比如Time，数据库里为空时，取回来值为{0001-01-01 00:00:00 +0000 UTC}，我如果返回这样一个数据，并不能确定是对是错。也可能我对这部分了解还太少了，有些”sql.NullTime“这种类型确实可以实现确定是否为空，这种类型在Golang中定义与DB关联的Struct常用的吗？在实际工程中，这部分定义是如何做的？
不好意思，我这个问题可能太多了，不应该放到这样一个issue里😄

**Comment by xxzhwl** [comment]
> ，

谢谢！！！回复速度好评！后面有Golang的问题，希望可以跟作者多交流🤭！

**Comment by liu-cn** [comment]
哈哈没关系，零值和nil这个确实在某些场景会引发问题，比如前端发送的请求，后端要求必须携带某字段，比如必须携带int类型的Status字段，此时有多种情况，可能为0，1，2，3.....还可能用户可能根本没携带该字段此时会被编码为零值也就是0，如果此时用户携带了该字段，但是也是为0时，go中的那个validator 验证器(https://github.com/go-playground/validator) 就会把用户携带了但是为0和根本没携带这两种情况都判定为用户没有携带该字段，如果要求此字段必填则该字段就过不了这个验证器的规则，此时解决方法就是把int类型的值换成指针类型*int，这时指针类型的零值为nil也就是说这时候用户没有携带时该字段为nil，携带了但是为0时是没关系的，是可以通过校验的，所以如果出现这种情况就用指针来区别就可以了，

至于sql.NullTime这个我在工程中基本没有用过，如果有这种可有可无的字段就用指针来区别就可以了，为nil就是没有。

**Comment by liu-cn** [comment]
哈哈，也欢迎一起优化代码，贡献代码，一起交流，一起学习，一起进步。

**Comment by xxzhwl** [comment]
好的好的，谢谢作者！
