### ISSUE TITLE
是否能对字段进行脱敏？

### ISSUE THREAD

**Issue by zhangyongding** [liu-cn/json-filter#4]
现在好像只支持不返回字段，但是在默写场景下可能需要对json的部分自动进行脱敏返回，不知道有没有办法支持

**Comment by liu-cn** [comment]
您好，可以详细描述一下您的需求和功能吗？比如这个自动进行脱敏返回是具体是什么意思，需要您结合业务场景详细的描述一下，谢谢。

**Comment by zhangyongding** [comment]
比如有一个结构体：
```
type People struct {
	NO       int
	Name     string
	IDCardNO string
}

var people = People{
	NO:       1,
	Name:     "张三",
	IDCardNO: "441400202211241234",
}

// to json: {NO:1, Name:"张三", IDCardNO:"******"}
```

要输出脱敏的字段是因为在记录日志的时候，身份证号作为敏感信息是不能记录的，但是如果IDCardNO不输出的话，又会被错误认为是没有这个值（{NO:1, Name:"张三"}）

**Comment by liu-cn** [comment]
抱歉此项目仅仅对字段进行过滤，你提的需求不是普遍需求，所以还是建议您在打印日志前自己手动复制一个结构体把敏感字段信息给处理掉，再过滤。

**Comment by liu-cn** [comment]
不是普遍需求

**Comment by liu-cn** [comment]
您好，现在新增了func选择器，可以实现您的需求，最新版本v1.8已经添加该功能，如果您用得上的话可以尝试一下，





具体用法



package main

import (
	"fmt"
	"github.com/liu-cn/json-filter/filter"
)

type People struct {
	NO       int    `json:"no"`
	Name     string `json:"name,select(log)"`
	IDCardNO string `json:"id_card_no,,select(log),func(GetHideID)"`
}

func (p People) GetHideID() string {
	return "*****"
}

var people = People{
	NO:       1,
	Name:     "张三",
	IDCardNO: "441400202211241234",
}

func filterPeople() {

	fmt.Println(filter.Select("log", &people))
	//{"id_card_no":"*****","name":"张三"}

	fmt.Println(people.IDCardNO)
	//441400202211241234
}

**Comment by liu-cn** [comment]
![image](https://user-images.githubusercontent.com/56096275/211717350-5a5eaa3d-11e2-4e4a-bf2b-bee9f723757b.png)

**Comment by liu-cn** [comment]
如果用的话，建议您看一下这个文件，https://github.com/liu-cn/json-filter/blob/main/example/func_test.go
上面用法写的很详细
