### ISSUE TITLE
定义baseModel的时候不生效

### ISSUE THREAD

**Issue by lewkamtao** [liu-cn/json-filter#5]
你好，我非常喜欢你这个框架，我几乎找了好久都没找到这样的框架来处理我的困扰，作为有代码洁癖的我，深深爱上了这个。

但是我遇到一个场景貌似卡住了，不知道是不是我使用方式不对，我尝试了好几次都不生效，当我定义一个BaseModel的时候，在BaseModel里面的字段失效了，但是其他的都没问题。

<img width="991" alt="image" src="https://user-images.githubusercontent.com/68851669/205484930-19cf93eb-e054-4dc4-878a-570fa1a9bd72.png">

最后希望作者可以继续维护下去，祝好～

**Comment by liu-cn** [comment]
好的，我已经看到您说的问题了，我现在正准备测试解决一下这个问题，解决后会给您反馈，另外我后面会持续优化和维护，包括后面考虑不影响使用的情况下加入缓存等功能，大幅度提升性能，谢谢您的支持，后面有什么问题和建议都可以给我反馈，我会及时处理

**Comment by liu-cn** [comment]
您好您方便把那个LocalTime的结构体给我看一下吗？

**Comment by lewkamtao** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/68851669/205485331-a18aaf7f-fb39-45eb-93cb-76e6f199919b.png">
我觉得一个是LocalTIme的问题，另外一个问题应该和LocalTime没关系，当我这样定义一个TestModel的时候他还是不会生效。

**Comment by lewkamtao** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/68851669/205485433-00473b9c-5e7b-416f-9a7f-1e28a0fdc645.png">
这是LocalTime的结构体

**Comment by liu-cn** [comment]
您好，我已经发现您的问题了，是您用法出了问题，需要在匿名结构体json的select前加一个逗号，因为select前面是字段名，如果匿名需要值为空，但是逗号不能省略，如果想把匿名结构体具名也是可以的可以直接在逗号前加字段名就可以，

**Comment by liu-cn** [comment]
![Snipaste_2022-12-04_18-21-14](https://user-images.githubusercontent.com/56096275/205485637-75ddc7d6-89cb-4bf2-9143-107f92d15e94.jpg)

**Comment by liu-cn** [comment]
![Snipaste_2022-12-04_18-28-12](https://user-images.githubusercontent.com/56096275/205485717-a8626272-8344-408f-9f4e-48bb4410e2d1.jpg)

**Comment by liu-cn** [comment]
我文档有写到这个，您可以再试试，框架没问题，后面有问题还可以继续给我说，也可以提建议，我会持续优化更新让功能变得更强大

**Comment by lewkamtao** [comment]
可以了，成功了

**Comment by liu-cn** [comment]
好的，感谢您的喜欢

**Comment by lewkamtao** [comment]
我这些warning是因为我使用方式问题吗？还是我应该关闭一些检测？
<img width="828" alt="image" src="https://user-images.githubusercontent.com/68851669/205486036-23e16818-f544-45f7-8ee0-00b8ccc4738b.png">

**Comment by lewkamtao** [comment]
另外，我看到您提供了filter.Time，太棒了！我把之前定义的时间格式去掉，用您提供的这个。

**Comment by liu-cn** [comment]
您的使用没问题，只不过是vscode的警告罢了，毕竟我的框架比较小众，vscode并不会兼容我的写法，我用的是goland，在goland的上面就不会有warning，这个warning只会影响观感别的不会影响什么，不会影响功能。

**Comment by liu-cn** [comment]
时间可以用我提供的也可以自己去实现也可以，

**Comment by liu-cn** [comment]
你好，我项目又进行了一波大更新，用法变得更简便了，新增了两个api，老方法依旧兼容，新项目加了缓存提升了40%的性能，https://www.bilibili.com/video/BV1s14y1G72v 这个是b站的视频讲解，你可以把你go项目里go.mod里我的库删了然后再同步下载一下这个库，就可以下载到最新版本的了，或者新创建一个项目体验一下新版本，新用法会更方便且性能更高。

**Comment by lewkamtao** [comment]
老哥 你就是神 谢谢啦 我持续关注着

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："notifications ***@***.***&gt;;
发送时间：2023年1月3日(星期二) 下午2:42
收件人："liu-cn/json-filter" ***@***.***&gt;;
抄送："lew ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [liu-cn/json-filter] 定义baseModel的时候不生效 (Issue #5)
-----------------------------------

 

 
你好，我项目又进行了一波大更新，用法变得更简便了，新增了两个api，老方法依旧兼容，新项目加了缓存提升了40%的性能，https://www.bilibili.com/video/BV1s14y1G72v 这个是b站的视频讲解，你可以把你go项目里go.mod里我的库删了然后再同步下载一下这个库，就可以下载到最新版本的了，或者新创建一个项目体验一下新版本，新用法会更方便且性能更高。
